ALTER TABLE public.player_applications
  ALTER COLUMN email DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS state_of_origin text,
  ADD COLUMN IF NOT EXISTS lga text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS nin text,
  ADD COLUMN IF NOT EXISTS nok_name text,
  ADD COLUMN IF NOT EXISTS nok_phone text,
  ADD COLUMN IF NOT EXISTS nok_relationship text,
  ADD COLUMN IF NOT EXISTS medical_conditions text,
  ADD COLUMN IF NOT EXISTS current_medications text,
  ADD COLUMN IF NOT EXISTS jersey_number text,
  ADD COLUMN IF NOT EXISTS previous_club_contact text,
  ADD COLUMN IF NOT EXISTS preferred_foot text,
  ADD COLUMN IF NOT EXISTS player_license text,
  ADD COLUMN IF NOT EXISTS highest_level text,
  ADD COLUMN IF NOT EXISTS fa_status text;